-- server/db/setup.sql

DROP TABLE IF EXISTS employee CASCADE;

CREATE TABLE IF NOT EXISTS employee();

CREATE TABLE IF NOT EXISTS job();

CREATE TABLE IF NOT EXISTS customer();

CREATE TABLE IF NOT EXISTS vehicle(
    make VARCHAR(40) NOT NULL,
    model VARCHAR(40) NOT NULL,
    year SMALLINT NOT NULL,
);